-- Simple admin credentials table (without RLS/policies).
-- Run in Supabase SQL Editor.

create table if not exists public.admin_credentials (
    id bigint generated by default as identity primary key,
    login text not null unique,
    password text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

-- Optional seed admin:
-- insert into public.admin_credentials (login, password, is_active)
-- values ('admin', 'admin123', true)
-- on conflict (login) do update
-- set password = excluded.password,
--     is_active = excluded.is_active;
